/* $NetBSD$ */

/*-
 * Copyright (c) 2018 Jason R. Thorpe
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _MEDIATEK_MT2701_PERICFGREG_H_
#define	_MEDIATEK_MT2701_PERICFGREG_H_

#define	MT7623_PERICFG_PADDR		0x10003000

/* Peripheral MD Power Down 1 Register */
#define	GLOBALCON_PDN_MD1_MASK		__BIT(0)
#define	GLOBALCON_PDN_MD2_MASK		__BIT(1)

/* Peripheral DCM Control Register */
#define	GLOBALCON_DCMCTL_DCM_ENABLE	    __BIT(0)
#define	GLOBALCON_DCMCTL_AXI_CLOCK_GATED_EN __BIT(1)
#define	GLOBALCON_DCMCTL_AHB_BUS_SLP_REQ_0  __BIT(4)
#define	GLOBALCON_DCMCTL_AHB_BUS_SLP_REQ_1  __BIT(5)
#define	GLOBALCON_DCMCTL_AHB_BUS_SLP_REQ_2  __BIT(6)
#define	GLOBALCON_DCMCTL_AHB_BUS_SLP_REQ_3  __BIT(7)
#define	GLOBALCON_DCMCTL_DCM_IDLE_BYPASS_EN_AP_DMA  __BIT(8)
#define	GLOBALCON_DCMCTL_DCM_IDLE_BYPASS_EN_AP_HIF  __BIT(9)
#define	GLOBALCON_DCMCTL_DCM_IDLE_BYPASS_EN_MID_HIF __BIT(10)
#define	GLOBALCON_DCMCTL_DCM_IDLE_BYPASS_EN_USB     __BIT(11)
#define	GLOBALCON_DCMCTL_DCM_IDLE_BYPASS_EN_MSDC    __BIT(12)

/* Peripheral DCM Debounce Counter */
#define	GLOBALCON_DCMDBC_DCM_DBC_CNT_MASK 0x7f
#define	GLOBALCON_DCMDBC_DCM_DBC_ENABLE	  __BIT(7)

/* Peripheral DCM Frequency Selection */
#define	GLOBALCON_DCMFSEL_QTR_MASK	0x7
#define	GLOBALCON_DCMFSEL_QTR(x)	((x) & GLOBALCON_DCMFSEL_QTR_MASK)
#define	GLOBALCON_DCMFSEL_HALF_MASK	0xf
#define	GLOBALCON_DCMFSEL_HALF(x)	(((x) & GLOBALCON_DCMFSEL_HALF_MASK) << 8)
#define	GLOBALCON_DCMFSEL_FULL_MASK	0x1f
#define	GLOBALCON_DCMFSEL_FULL(x)	(((x) & GLOBALCON_DCMFSEL_FULL_MASK) << 16)

/* Peripheral Clock Selection */
#define	GLOBALCON_CKSEL_PERIBUS_CK_SEL	__BIT(0)

/* Peripheral AXI Bus Control 1 */
#define	BUS_CTL1_AHB1_SHARE_EN_DBGAHB	__BIT(25)
#define	BUS_CTL1_AHB1_SHARE_EN_ETH	__BIT(26)
#define	BUS_CTL1_AHB1_SHARE_EN_USB1	__BIT(27)
#define	BUS_CTL1_AHB0_SHARE_EN_PWM	__BIT(28)
#define	BUS_CTL1_AHB0_SHARE_EN_SPM	__BIT(29)
#define	BUS_CTL1_AHB0_SHARE_EN_NFI	__BIT(30)
#define	BUS_CTL1_AHB0_SHARE_EN_USB0	__BIT(31)

/* Peripheral AXI Bus Control 2 */
#define	BUS_CTL2_AHB_MERGE_EN_MASK	0x7f
#define	BUS_CTL2_AHB_MERGE_EN(x)	((x) & BUS_CTL2_AHB_MERGE_EN_MASK)
#define	BUS_CTL2_AHB_BUFFER_EN_MASK	0x7f
#define	BUS_CTL2_AHB_BUFFER_EN(x)	(((x) & BUS_CTL2_AHB_BUFFER_EN_MASK) << 7)
#define	BUS_CTL2_AHB_SECURE_EN_MASK	0x7f
#define	BUS_CTL2_AHB_SECURE_EN(x)	(((x) & BUS_CTL2_AHB_SECURE_EN_MASK) << 14)
#define	BUS_CTL2_AHB2_SHARE_EN_THERM	__BIT(28)
#define	BUS_CTL2_AHB2_SHARE_EN_MSDC1	__BIT(29)
#define	BUS_CTL2_AHB2_SHARE_EN_SPI1	__BIT(30)
#define	BUS_CTL2_AHB2_SHARE_EN_SPI0	__BIT(31)

/* Peripheral AXI SI0/SI1 Control */
#define	BUS_SIn_CTL_OUTSTANDING_DISABLE	__BIT(0)
#define	BUS_SIn_CTL_WAY_EN_MASK		0x3
#define	BUS_SIn_CTL_WAY_EN(x)		(((x) & BUS_SI0_CTL_WAY_EN_MASK) << 8)
#define	BUS_SIn_CTL_CTRL_BYPASS		__BIT(12)
#define	BUS_SIn_CTL_B_CHNL_SEL_MASK	0x7
#define	BUS_SIn_CTL_B_CHNL_SEL(x)	(((x) & BUS_SI0_CTL_B_CHNL_SEL_MASK) << 13)
#define	BUS_SIn_CTL_R_CHNL_SEL_MASK	0x7
#define	BUS_SIn_CTL_R_CHNL_SEL(x)	(((x) & BUS_SI0_CTL_R_CHNL_SEL_MASK) << 16)
#define	BUS_SIn_CTL_D_FSLV_SET_RIRQ	__BIT(19)
#define	BUS_SIn_CTL_D_FSLV_SET_WIRQ	__BIT(20)
#define	BUS_SIn_CTL_D_FSLV_SET_BID_MISS	__BIT(21)
#define	BUS_SIn_CTL_D_FSLV_SET_RID_MISS	__BIT(22)
#define	BUS_SIn_CTL_RD_OT_BUSY		__BIT(23)
#define	BUS_SIn_CTL_WR_OT_BUSY		__BIT(24)
#define	BUS_SI0_CTL_CG_DISABLE		__BIT(31)

/* Peripheral AXI MI Status */
#define	MI_STA_MI0_ERRMID_SET_RIRQ	__BIT(0)
#define	MI_STA_MI0_ERRMID_SET_BIRQ	__BIT(1)
#define	MI_STA_MI0_R_BUSY		__BIT(2)
#define	MI_STA_MI0_W_BUSY		__BIT(3)
#define	MI_STA_MI1_ERRMID_SET_RIRQ	__BIT(4)
#define	MI_STA_MI2_ERRMID_SET_BIRQ	__BIT(5)
#define	MI_STA_MI3_R_BUSY		__BIT(6)
#define	MI_STA_MI4_W_BUSY		__BIT(7)

/* XXX Bandwidth Limiter regsiters XXX */

/* Peripheral USB Wakeup Control 0 */
#define	USB_WAKEUP_DEC_CON0_USB0_CDEN	__BIT(0)
#define	USB_WAKEUP_DEC_CON0_USB0_CDDEBOUNCE_MASK 0xf
#define	USB_WAKEUP_DEC_CON0_USB0_CDDEBOUNCE(x) (((x) & USB_WAKEUP_DEC_CON0_USB0_CDDEBOUNCE_MASK) << 1)

/* Peripheral UART Clock Source Selection */
/* 0 = 26MHz, 1 = 52MHz */
#define	UART_CLK_SOURCE_SEL_UART0	__BIT(0)
#define	UART_CLK_SOURCE_SEL_UART1	__BIT(1)
#define	UART_CLK_SOURCE_SEL_UART2	__BIT(2)
#define	UART_CLK_SOURCE_SEL_UART3	__BIT(3)

/* Peripheral ETH_NIC Control */
#define	ETH_NIC_CON_MII_MODE_MASK	0xf
#define	ETH_NIC_CON_MII_MODE(x)		((x) & ETH_NIC_CON_MII_MODE_MASK)

/* Peripheral NFI Clock Source Selection */
#define	NFI_CK_SOURCE_SEL		__BIT(0)

/* Peripheral NFI MAC Control */
#define	NFI_MAC_CTRL_MASK		0x1f
#define	NFI_MAC_CTRL(x)			((x) & NFI_MAC_CTRL_MASK)

#endif /* _MEDIATEK_MT2701_PERICFGREG_H_ */
